vitalDB_signal extractor_for Dr.Hwang
https://vitaldb.net/

Brief Summary

############################################################################################################
############################################################################################################
#  1.input your file name (.vital)
#  2.select specific time
#  3.get specific signals                                    → Replace values as you want 
############################################################################################################
############################################################################################################

In [1]:
# import libaries
import os
import csv
import glob
import datetime
import numpy as np
import AMCVitalReader as vr

In [2]:
############################################################################################################
############################################################################################################
#  1.input your file name (.vital)
fname = 'F-07_180502_145342_normal'
############################################################################################################
############################################################################################################

# get header data
vr_data = vr.vital_reader(fname+'.vital')
vr_data.read_header()
vr_data.read_packets()

# get time data
a,b = vr_data.read_number_datetime('Intellivue','HR')
print("[time start]",a[0])
print("[time end]",a[-1])
print("[time length]",a[-1]-a[0])

[time start] 2018-05-02 15:02:15.526000
[time end] 2018-05-02 17:40:33.951000
[time length] 2:38:18.425000

In [3]:
############################################################################################################
############################################################################################################
#  2.select specific time     
start_year   = 2018 #
start_month  = 5    #
start_date   = 2    #
start_hour   = 15
start_minute = 15
start_second = 0

end_year     = start_year   
end_month    = start_month
end_date     = start_date
end_hour   = 15
end_minute = 16
end_second = 0
############################################################################################################
############################################################################################################

In [4]:
############################################################################################################
############################################################################################################
#  3.get specific signals
#  blank if no signal to input

# device0 : DI-1120
device0_name   = 'DI-1120'
device0_signal = ['VOLT']
#  blank if no signal to input []

# device1 : Intellivue
device1_name   = 'Intellivue'
device1_signal = ['ECG_HR',
                  'PLETH_HR',
                  'AWAY_CO2_INSP_MIN',
                  'O2_ET_PERC',
                  'O2_INSP_PERC',
                  'N2O_ET',
                  'N2O_INSP',
                  'RR']
#  blank if no signal to input []

# device2 : Primus
device2_name   = 'Primus'
device2_signal = ['CO2']
#  blank if no signal to input []

############################################################################################################
############################################################################################################
# # device0 : DI-1120
# device0_name   = 'DI-1120'
# device0_signal = ['VOLT']


# # device1 : Intellivue
# device1_name   = 'Intellivue'
# device1_signal = ['ECG_HR',
#                   'PLETH_HR',
#                   'AWAY_CO2_INSP_MIN',
#                   'O2_ET_PERC',
#                   'O2_INSP_PERC',
#                   'N2O_ET',
#                   'N2O_INSP',
#                   'RR']
# # device2 : Primus
# device2_name   = 'Primus'
# device2_signal = ['CO2']

# 변수설명입니다.
# Device name/variable 이렇게 정리했습니다.

# DI-1120/VOLT 호흡음/심음

# Intellivue/ECG_HR 심전도 맥박수
# Intellivue/PLETH_SAT_O2 광혈류측정기 산소포화도
# Intellivue/PLETH_HR 광혈류측정기(PPG) 맥박수
# Intellivue/PLETH_PERF_REL ??
# Intellivue/AWAY_CO2_ET 호기말 이산화탄소분압
# Intellivue/AWAY_CO2_INSP_MIN 흡기 이산화탄소
# Intellivue/O2_ET_PERC 호기말 산소 퍼센트
# Intellivue/O2_INSP_PERC 흡기 산소 퍼센트
# Intellivue/N2O_ET 호기말 아산화질소분압
# Intellivue/N2O_INSP 흡기 아산화질소
# Intellivue/ST_II 심전도 lead 2 의 ST
# Intellivue/RR 호흡수
# Intellivue/ABP_MEAN 평균동맥압(침습적)
# Intellivue/NIBP_SYS 비침습적 수축기혈압
# Intellivue/NIBP_DIA 비침습적 이완기혈압
# Intellivue/NIBP_MEAN 비침습적 평균혈압
# Intellivue/NIBP_HR 비침습적 맥박수
# Intellivue/ABP_SYS 침습적 수축기동맥압
# Intellivue/ABP_DIA 침습적 이완기동맥압
# Intellivue/HR 맥박수
# Intellivue/DES_ET_PERC 호기말 
# Intellivue/DES_INSP_PERC desflurane
# Intellivue/PPV 흡기
# Intellivue/TEMP desflurane 압변동(pulse pressure variation)

# Primus/SET_TV_L 체온
# Primus/SET_PEEP 일호흡량(tidal volume)
# Primus/PAMB_MBAR 호기말양압(positive end-expiratory pressure)
# Primus/VENT_LEAK 인공호흡기 누출
# Primus/SET_FIO2 산소분율
# Primus/SET_FRESH_FLOW 인공호흡기 fresh flow
# Primus/MAWP_MBAR 평균기도압(MBAR)
# Primus/MAC 최소폐포농도(minimal alveolar concentration)
# Primus/MV 분당환기량(minute ventilation)
# Primus/RR_VF ??
# Primus/INCO2 흡기 이산화탄소
# Primus/ETCO2 호기 이산화탄소
# Primus/FIN2O 흡기 아산화질소분압
# Primus/FEN2O 호기 아산화질소분압
# Primus/FEO2 호기 산소분압
# Primus/FIO2 흡입산소분율
# Primus/PIP_MBAR 최고흡기압력(peak inspiratory pressure)
# Primus/TV 일호흡량(tidal volume)
# Primus/COMPLIANCE 유순도 
# Primus/PPLAT_MBAR 고평부압력(plateau perssure)
# Primus/PEEP_MBAR 호기말양압(MBAR)
# Primus/RR_CO2 호흡수
# Primus/CO2 이산화탄소
# Primus/AWP 기도압력
# Primus/INSP_DES 흡기 desflurane
# Primus/EXP_DES 호기 desflurane 
# Primus/SET_INSP_TM 흡기 시간
# Primus/SET_RR_IPPV 비침습적 간헐적 양압환기법(intermittent positive pressure ventilation)
# Primus/SET_INTER_PEEP 
# Primus/SET_PIP 최대흡기압력(peak inspiratory pressure)
# Primus/SET_INSP_PAUSE 흡기 정지

fname_with_time = fname+'_'+str(start_hour)+':'+str(start_minute)+':'+str(start_second)+'to'+str(end_hour)+':'+str(end_minute)+':'+str(end_second)
print('[fname_with_time]',fname_with_time)
print('total',len(device0_signal),'signal(s) from',device0_name)
print('total',len(device1_signal),'signal(s) from',device1_name)
print('total',len(device2_signal),'signal(s) from',device2_name)

[fname_with_time] F-07_180502_145342_normal_15:15:0to15:16:0
total 1 signal(s) from DI-1120
total 8 signal(s) from Intellivue
total 1 signal(s) from Primus

In [5]:
signal_table=[]
table_label=[]
# print(signal_table)
# print(table_label)

for i in range(0,len(device0_signal)+len(device1_signal)+len(device2_signal)):
    if i<len(device0_signal):
        print('i=',i,', device0')
        temp = vr_data.read_wave_datetime_interval(device0_name,device0_signal[i],datetime.datetime(start_year,start_month,start_date,start_hour,start_minute,start_second),datetime.datetime(end_year,end_month,end_date,end_hour,end_minute,end_second))
        signal_table.append(temp[0])
        signal_table.append(temp[1])
        table_label.append("Time")
        table_label.append(device0_signal[i])
        
    elif i<len(device0_signal)+len(device1_signal):
        print('i=',i,', device1')
        temp = vr_data.read_number_datetime_interval(device1_name,device1_signal[i-len(device0_signal)],datetime.datetime(start_year,start_month,start_date,start_hour,start_minute,start_second),datetime.datetime(end_year,end_month,end_date,end_hour,end_minute,end_second))
        signal_table.append(temp[0])
        signal_table.append(temp[1])    
        table_label.append("Time")
        table_label.append(device1_signal[i-len(device0_signal)])
    else:
        print('i=',i,', device2')
        temp = vr_data.read_number_datetime_interval(device2_name,device2_signal[i-len(device0_signal)-len(device1_signal)],datetime.datetime(start_year,start_month,start_date,start_hour,start_minute,start_second),datetime.datetime(end_year,end_month,end_date,end_hour,end_minute,end_second))
        signal_table.append(temp[0])
        signal_table.append(temp[1])
        table_label.append("Time")
        table_label.append(device2_signal[i-len(device0_signal)-len(device1_signal)])

i= 0 , device0
i= 1 , device1
i= 2 , device1
i= 3 , device1
i= 4 , device1
i= 5 , device1
i= 6 , device1
i= 7 , device1
i= 8 , device1
i= 9 , device2

In [6]:
from itertools import zip_longest
signal_table_column=list(zip_longest(*signal_table))

csv_file = open(fname_with_time+'.csv', 'w')
with csv_file:
    writer = csv.writer(csv_file)
    writer.writerow(table_label)
    writer.writerows(signal_table_column)

print("Writing complete")

Writing complete

In [7]:
import pandas as pd
data = pd.read_csv(fname_with_time+'.csv', index_col=False)
data.head(10)

/home/keewon/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (2,4,6,8,10,12,14,16,18) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Time,VOLT,Time.1,ECG_HR,Time.2,PLETH_HR,Time.3,AWAY_CO2_INSP_MIN,Time.4,O2_ET_PERC,Time.5,O2_INSP_PERC,Time.6,N2O_ET,Time.7,N2O_INSP,Time.8,RR,Time.9,CO2
0,2018-05-02 15:15:00.000200,0.186169,2018-05-02 15:15:00.047000,71.0,2018-05-02 15:15:00.047000,71.0,2018-05-02 15:15:00.047000,1.0,2018-05-02 15:15:00.047000,54.0,2018-05-02 15:15:00.047000,58.0,2018-05-02 15:15:00.047000,0.0,2018-05-02 15:15:00.047000,0.0,2018-05-02 15:15:00.047000,13.0,2018-05-02 15:15:00.190051,30.0
1,2018-05-02 15:15:00.000600,0.184948,2018-05-02 15:15:01.071000,71.0,2018-05-02 15:15:01.071000,71.0,2018-05-02 15:15:01.071000,1.0,2018-05-02 15:15:01.071000,54.0,2018-05-02 15:15:01.071000,58.0,2018-05-02 15:15:01.071000,0.0,2018-05-02 15:15:01.071000,0.0,2018-05-02 15:15:01.071000,13.0,2018-05-02 15:15:00.670051,30.0
2,2018-05-02 15:15:00.001000,0.183727,2018-05-02 15:15:02.095000,71.0,2018-05-02 15:15:02.095000,71.0,2018-05-02 15:15:02.095000,1.0,2018-05-02 15:15:02.095000,54.0,2018-05-02 15:15:02.095000,58.0,2018-05-02 15:15:02.095000,0.0,2018-05-02 15:15:02.095000,0.0,2018-05-02 15:15:02.095000,13.0,2018-05-02 15:15:01.150051,30.0
3,2018-05-02 15:15:00.001400,0.178844,2018-05-02 15:15:03.119000,71.0,2018-05-02 15:15:03.119000,71.0,2018-05-02 15:15:03.119000,1.0,2018-05-02 15:15:03.119000,52.0,2018-05-02 15:15:03.119000,57.0,2018-05-02 15:15:03.119000,0.0,2018-05-02 15:15:03.119000,0.0,2018-05-02 15:15:03.119000,13.0,2018-05-02 15:15:01.630051,30.0
4,2018-05-02 15:15:00.001800,0.173961,2018-05-02 15:15:04.143000,71.0,2018-05-02 15:15:04.143000,71.0,2018-05-02 15:15:04.143000,1.0,2018-05-02 15:15:04.143000,52.0,2018-05-02 15:15:04.143000,57.0,2018-05-02 15:15:04.143000,0.0,2018-05-02 15:15:04.143000,0.0,2018-05-02 15:15:04.143000,13.0,2018-05-02 15:15:02.110051,30.0
5,2018-05-02 15:15:00.002200,0.170298,2018-05-02 15:15:05.167000,71.0,2018-05-02 15:15:05.167000,71.0,2018-05-02 15:15:05.167000,1.0,2018-05-02 15:15:05.167000,52.0,2018-05-02 15:15:05.167000,57.0,2018-05-02 15:15:05.167000,0.0,2018-05-02 15:15:05.167000,0.0,2018-05-02 15:15:05.167000,13.0,2018-05-02 15:15:02.590051,30.0
6,2018-05-02 15:15:00.002600,0.167857,2018-05-02 15:15:06.191000,71.0,2018-05-02 15:15:06.191000,71.0,2018-05-02 15:15:06.191000,1.0,2018-05-02 15:15:06.191000,52.0,2018-05-02 15:15:06.191000,57.0,2018-05-02 15:15:06.191000,0.0,2018-05-02 15:15:06.191000,0.0,2018-05-02 15:15:06.191000,13.0,2018-05-02 15:15:03.070051,30.0
7,2018-05-02 15:15:00.003000,0.165415,2018-05-02 15:15:07.215000,71.0,2018-05-02 15:15:07.215000,71.0,2018-05-02 15:15:07.215000,1.0,2018-05-02 15:15:07.215000,52.0,2018-05-02 15:15:07.215000,57.0,2018-05-02 15:15:07.215000,0.0,2018-05-02 15:15:07.215000,0.0,2018-05-02 15:15:07.215000,13.0,2018-05-02 15:15:03.550051,30.0
8,2018-05-02 15:15:00.003400,0.165415,2018-05-02 15:15:08.239000,71.0,2018-05-02 15:15:08.239000,71.0,2018-05-02 15:15:08.239000,1.0,2018-05-02 15:15:08.239000,52.0,2018-05-02 15:15:08.239000,57.0,2018-05-02 15:15:08.239000,0.0,2018-05-02 15:15:08.239000,0.0,2018-05-02 15:15:08.239000,13.0,2018-05-02 15:15:04.030051,30.0
9,2018-05-02 15:15:00.003800,0.166636,2018-05-02 15:15:09.263000,71.0,2018-05-02 15:15:09.263000,71.0,2018-05-02 15:15:09.263000,1.0,2018-05-02 15:15:09.263000,52.0,2018-05-02 15:15:09.263000,57.0,2018-05-02 15:15:09.263000,0.0,2018-05-02 15:15:09.263000,0.0,2018-05-02 15:15:09.263000,12.0,2018-05-02 15:15:04.510051,30.0